# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NLUTrain@0
  inputs:
    service: luis
    utterances: models/utterances.json
    modelSettings: models/settings.luis.json
- task: NLUTest@0
  inputs:
    service: luis
    utterances: models/tests.json
    modelSettings: models/settings.luis.json
    publishTestResults: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    artifactType: container
- task: NLUClean@0
  inputs:
    service: luis
