# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NLUDevOps@0
  inputs:
    command: train
    service: luis
    utterances: models/utterances.json
    serviceSettings: models/settings.luis.json
- task: NLUDevOps@0
  inputs:
    command: clean
    service: luis
