trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /extensions/
    - /pipelines/extension-build.yml
pr:
  branches:
    include:
    - master
  paths:
    include:
    - /extensions/
    - /pipelines/extension-build.yml

stages:
- stage: Build_private
  jobs:
  - job: build_vsix
    pool:
      vmImage: 'ubuntu-latest' 
    steps:
    - task: NPM@1
      displayName: npm install
      inputs:
        command: install
        workingDir: extensions

    - task: NPM@1
      displayName: npm run lint
      inputs:
        command: custom
        customCommand: run lint
        workingDir: extensions

    - task: NPM@1
      displayName: npm run build
      inputs:
        command: custom
        customCommand: run build
        workingDir: extensions

    - task: CopyFiles@2
      displayName: Stage extension artifact for publish
      inputs:
        sourceFolder: extensions
        contents: '**/*.vsix'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishPipelineArtifact@0
      displayName: Publish extension artifact
      inputs:
        artifactName: drop
        targetPath: $(Build.ArtifactStagingDirectory)

    - task: TfxInstaller@2
      displayName: 'Install Node CLI'

    - task: PublishAzureDevOpsExtension@2
      displayName: 'Publish Extension'
      inputs:
        connectedServiceName: marketplaceConnection
        fileType: vsix
        vsixFile: '**/*.vsix'
        publisherId: NLUDevOps
        extensionId: NLUDevOpsCI
        extensionName: NLU.DevOps.CI
        extensionVersion: '0.1.$(Build.BuildId)'
        updateTasksVersion: true
        extensionVisibility: private
        shareWith: NLUDevOps

