trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /pipelines/nlu-extension.yml
    - /models
    - /src
pr:
  branches:
    include:
    - master
  paths:
    include:
    - /pipelines/nlu-extension.yml
    - /models
    - /src

steps:
- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages for NLU.DevOps
  inputs:
    command: restore
    projects: src/NLU.DevOps.sln

- task: DotNetCoreCLI@2
  displayName: Create NuGet package for NLU.DevOps.CommandLine
  inputs:
    command: pack
    packagesToPack: src/NLU.DevOps.CommandLine
    configuration: Release

- task: DotNetCoreCLI@2
  displayName: Create NuGet package for NLU.DevOps.MockProvider
  inputs:
    command: pack
    packagesToPack: src/NLU.DevOps.MockProvider
    configuration: Release

- task: DotNetCoreCLI@2
  displayName: Install dotnet-nlu-mock
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-nlu-mock --add-source $(Build.ArtifactStagingDirectory) --tool-path $(Agent.TempDirectory)/.dotnet

- task: NLUTrain@0
  displayName: Train NLU model
  inputs:
    service: mock
    utterances: models/utterances.json
    nupkgPath: $(Build.ArtifactStagingDirectory)

- task: NLUTest@0
  displayName: Test NLU model
  inputs:
    service: mock
    utterances: models/tests.json
    nupkgPath: $(Build.ArtifactStagingDirectory)
    publishTestResults: true
    publishNLUResults: true

- task: NLUClean@0
  displayName: Cleanup the NLU service
  inputs:
    service: mock
    nupkgPath: $(Build.ArtifactStagingDirectory)
