trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /pipelines/nlu-extension.yml
    - /models
    - /src
pr:
  branches:
    include:
    - master
  paths:
    include:
    - /pipelines/nlu-extension.yml
    - /models
    - /src

steps:
- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages for NLU.DevOps
  inputs:
    command: restore
    projects: src/NLU.DevOps.sln

- task: DotNetCoreCLI@2
  displayName: Create NuGet package for NLU.DevOps.CommandLine
  inputs:
    command: pack
    packagesToPack: src/NLU.DevOps.CommandLine
    configuration: Release

- task: AzurePowerShell@4
  displayName: Get ARM token for Azure
  condition: and(succeeded(), ne(variables['nlu.ci'], 'false'))
  inputs:
    azureSubscription: $(azureSubscription)
    azurePowerShellVersion: latestVersion
    scriptType: inlineScript
    inline: |
      $azProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile
      $currentAzureContext = Get-AzContext
      $profileClient = New-Object Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient($azProfile)
      $token = $profileClient.AcquireAccessToken($currentAzureContext.Tenant.TenantId)
      $setVariableMessage = "##vso[task.setvariable variable=arm_token]{0}" -f $token.AccessToken 
      echo $setVariableMessage

- task: NLUTrain@0
  displayName: Train NLU model
  inputs:
    service: $(nlu.service)
    utterances: models/utterances.json
    modelSettings: models/settings.$(nlu.service).json
    nupkgPath: $(Build.ArtifactStagingDirectory)

- task: NLUTest@0
  displayName: Test NLU model
  inputs:
    service: $(nlu.service)
    utterances: models/tests.json
    nupkgPath: $(Build.ArtifactStagingDirectory)
    publishTestResults: true
    publishNLUResults: true

- task: NLUClean@0
  displayName: Cleanup the NLU service
  condition: and(always(), ne(variables['nlu.ci'], 'false'))
  inputs:
    service: $(nlu.service)
    nupkgPath: $(Build.ArtifactStagingDirectory)
