// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1812:Avoid uninstantiated internal classes", Justification = "The class is passed as a generic type parameter that has a new constraint.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.Clean.CleanOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1812:Avoid uninstantiated internal classes", Justification = "The class is passed as a generic type parameter that has a new constraint.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.Compare.CompareOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1812:Avoid uninstantiated internal classes", Justification = "The class is passed as a generic type parameter that has a new constraint.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.Test.TestOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1812:Avoid uninstantiated internal classes", Justification = "The class is passed as a generic type parameter that has a new constraint.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.TestSpeech.TestSpeechOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1812:Avoid uninstantiated internal classes", Justification = "The class is created through late-bound reflection.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.Test.TestCommand.LabeledUtteranceWithSpeechFile")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1812:Avoid uninstantiated internal classes", Justification = "The class is passed as a generic type parameter that has a new constraint.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.Train.TrainOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:OpeningParenthesisMustBeSpacedCorrectly", Justification = "The params C# keyword should be included as an exemption for C# 7 value tuples.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.Compare.CompareCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:ClosingParenthesisMustBeSpacedCorrectly", Justification = "Generics over value tuples should be included as an exemption for C# 7.", Scope = "type", Target = "~T:NLU.DevOps.CommandLine.Test.TestCommand")]
